heat_template_version: 2016-04-08

description: >
  OpenStack Aodh API service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  AodhBase:
    type: ./aodh-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Aodh API service.
    value:
      service_name: aodh_api
      config_settings:
        map_merge:
          - get_attr: [AodhBase, role_data, config_settings]
          - aodh::wsgi::apache::ssl: false
            aodh::api::service_name: 'httpd'
            aodh::api::keystone_tenant: 'service'
          - tripleo.aodh_api.firewall_rules:
              '128 aodh-api':
                dport:
                  - 8042
                  - 13042

      step_config: |
        include tripleo::profile::base::aodh::api
